version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge