version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network
  goapp:
    container_name: goapp
    build:
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=auctions
      - BATCH_INSERT_INTERVAL=7m
      - MAX_BATCH_SIZE=10
      - AUCTION_DURATION_SECONDS=15
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge