version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rate-limiter-net

  goapp:
    container_name: goapp
    build: .
    environment:
      - STORAGE_TYPE=redis # ou "memory" para usar armazenamento em memória
      - RATE_LIMIT_IP=5
      - RATE_LIMIT_TOKEN=10
      - BLOCK_TIME=300
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - rate-limiter-net

volumes:
  redis_data:

networks:
  rate-limiter-net:
    driver: bridge