scrape_configs:
  - job_name: 'otel-collector'
    scrap_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'goapp'
    scrap_interval: 10s
    static_configs:
      - targets: ['goapp:8080']