version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
  service1:
    container_name: service1
    build:
      context: /service1
      dockerfile: Dockerfile
    environment:
      - SERVICE2_API=http://service2:8181/cep/%s
      - HTTP_PORT=:8080
      - OTEL_EXPORTER_OTLP_ENPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=Service1
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
      - service2
      - zipkin

  service2:
    container_name: service2
    build:
      context: /service2
      dockerfile: Dockerfile
    environment:
      - WEATHER_API_KEY=MINHA-KEY
      - HTTP_PORT=:8181
      - VIA_CEP_API=http://viacep.com.br/ws/%s/json/
      - WEATHER_API=http://api.weatherapi.com/v1/current.json?q=%s&key=%s
      - OTEL_EXPORTER_OTLP_ENPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=Service2
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "8181:8181"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
      - zipkin