scrape_configs:
  - job_name: 'otel-collector'
    scrap_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'service1'
    scrap_interval: 10s
    static_configs:
      - targets: ['service1:8080']